[package]
edition = "2021"
name = "github_host"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_user_agent = "0.1.0"
regex = "1.8.1"
reqwest = {version = "0.11", features = ["blocking"]}
